package exceptionPractice;

public class TryandCatchblocks {

	
public	 class xyz{
	static void m1() {
		          try {}
		          catch(Exception e) {}
	}
	 }
	public static void main(String[] args) {
//		       try {
//		    	    
//		       }
//		       catch(Throwable t){}
//		       finally {}
		       //case#2
//		       try {}
//		       finally {}
		//       catch(Exception e) {}// it must be place in after try becz we know finally is the last one 
		       //case#3
		   //    try {}
		       //case#4
		       
		 //      catch(Exception e) {}
		//case#5
	//
		
		
		//finally {}
		
//		try {}
//		//int a=10;
//		catch(Exception e) {}
//		//int b=20;
//	//	finally {}
//		finally {}
		
		
		                     try {}
		                     catch(Exception e) {}
		               //      catch(ArithmeticException ae) {}
			

	}

}
